/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const defaultProjectId = "sljhxzqrgrqnrwpdoxuc";
const defaultAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsamh4enFyZ3JxbnJ3cGRveHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Nzc0MDcsImV4cCI6MjA3MDQ1MzQwN30.R4IMUzh1i02VAunGIklyEjLdmnnLo4L05lResSM3nOo";

export const projectId = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined)?.trim() || defaultProjectId;
export const publicAnonKey =
	(import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim() || defaultAnonKey;